### ISSUE TITLE
mail.ru директ и другая реклама...

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#10809]
<img src="https://monosnap.com/file/7QD4FhkNUpcaZYNtgQVz1h4rIv3Osf.png">
На счет кнопок "установить" разве фильтр раздражителей не должен это блокировать?

**Comment by densik3799** [comment]
Доброе утро!)Мне уже Алекс помог и обновил фильтры и раздражители заработали и всё по убирал!)))Спасибо Вам огромное за Вашу помощь!!!!Вот с этими рекламами ничего не выходит и  раздражитель стоит и блокирует и новые выскакивают(((http://purum-pup-pum.ru/full/ Вы извините за эротику,но хотел проверить где много баннеров а оно не блокирует(  densik   02.02.2018, 08:05, "Smorvel" <notifications@github.com>:На счет кнопок "установить" разве фильтр раздражителей не должен это блокировать?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Alex-302** [comment]
Реклама и полоса сверху блокируются. У тебя похоже сработал детект блокировщика, и имена элементов зашифровались.

Баннер снизу слева убрал
