### ISSUE TITLE
https://retetecugust.com/ - Cannot Whitelist

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11475]
***Description***:
* **Current behaviour**: 

Does not load ads even when whitelisted. 
<details><summary>Screenshot:</summary>
![qu5yt](https://user-images.githubusercontent.com/33634917/36115654-62787ed4-103c-11e8-8c4d-3f835daa2f8f.png)

</details><br/>

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Mac 10.13
Browser:                               | Chrome
AdGuard version:                       | 1.5.3
Filters enabled:                       | English, Spyware, Annoyances, Useful ads & self-promotion, French, Safari, EasyList, EasyPrivacy, Fanboy SBL, Fanboy Annoyances, EasyList Italy, Liste FR, ROList, Fanboy's Enhanced Tracking List, ROLIST2, Adblock Warning Removal List, Spam404, road-block
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1756003

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't open this site.
@AdamWr please take a look.

**Comment by AdamWr** [comment]
It seems that these ads don't load, because these requests are blocked:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/36162907-04b665e8-10e8-11e8-9fdf-a713df60a09a.png)

</details>
<br>

These rules should fix it:
`@@||retetecugust.com^$document`
`@@||googlesyndication.com^$domain=googleads.g.doubleclick.net`
but I'm not sure if it is good solution.

**Comment by BlazDT** [comment]
Can we close the issue?
