### ISSUE TITLE
movieslegacy.com

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#117080]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for Android, AdGuard for Windows

### AdGuard version

4.3.3

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://movieslegacy.com/x-men-collection-1080p-1080p-10bit-1080p-60fps-2160p-bluray-enghindi/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

![9C6439F4-3D4E-4D56-83F5-5120331FBEED](https://user-images.githubusercontent.com/46019727/166119616-e9120d5d-26ff-447a-87a1-202a5e2c926b.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce. We have the necessary rules for this site, but on iOS advanced rules sometimes executed too late. Maybe this is your case.
Also please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds, because iOS will breaks configuration process.
