### ISSUE TITLE
The Hindu app - missed ads

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#14556]
### Issue URL (Incorrect Blocking)
[https://itunes.apple.com/kw/app/the-hindu/id584786636?mt=8](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fitunes.apple.com%2Fkw%2Fapp%2Fthe-hindu%2Fid584786636%3Fmt%3D8)
### Comment
> Unable to block ads on “the hindu” app..it allows internet connection to the app with ads or it won’t allow the internet access to the app.. it is like allow all or block all. Kindly resolve the issue.
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/p9wNYsw.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/fPeITlX.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | iOS
AdGuard version: | 2.0.2.146
Browser: | The App Store app
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | Default
Filters: | English,<br>Spyware,<br>Social media,<br>Mobile Ads,<br>Safari,<br>Annoyances

**Comment by AdamWr** [comment]
These ads looks like Google ads and I think should be blocked by AdGuard DNS.
On iPad this app looks different, but ads are blocked on my end, instead of ads I have empty black space at the bottom, but we can't hide it.

<details><summary>Screenshot with AdGuard DNS enabled</summary>

![the_hindu_app1](https://user-images.githubusercontent.com/29142494/38669305-4e6c9064-3e46-11e8-95e4-7288ab09587e.jpeg)

</details>
<br>

<details><summary>Screenshot with AdGuard DNS disabled</summary>

![the_hindu_app2](https://user-images.githubusercontent.com/29142494/38669410-964c0d7e-3e46-11e8-954b-7979f5bd75db.jpeg)

</details>

**Comment by Alex-302** [comment]
@evgeniy-ADG user can try full tunnel mode.
