### ISSUE TITLE
deviantart.com

### ISSUE THREAD

**Issue by User1X1** [AdguardTeam/AdguardFilters#162102]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.52.0 on Chrome 117.0.5938.89 (64 bits)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.deviantart.com/somebody2978/art/Cammy-and-Chun-Li-in-England-1994-FullHD-867428983

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. "AdGuard - Annoyances -> AdGuard - Other Annoyances", has errors with DeviantArt. When you enter any image publication, you scroll down, the page creates that error and deletes the suggestions of other publications.

2. Screenshots
https://images2.imgbox.com/ff/56/rxpmZv5F_o.jpg

### Privacy

- [X] I agree to follow this condition

**Comment by Riffz** [comment]
This is happening to me too.

This appears to be caused by https://github.com/AdguardTeam/AdguardFilters/commit/7e282b7261f4c889075d29bbce8913a46fe1a1f7 which was introduced as part of https://github.com/AdguardTeam/AdguardFilters/issues/157292.  I'm not able to figure out enough about how filter rules work to know why, but when digging into the logger I see the rule that was introduced by that PR.

I've been able to replicate the issue rather reliably.  I don't need to be logged in to replicate it.  I just need to scroll down after a page with artwork on it finishes loading and the sidebar is replaced with the error message and the ns binding error shows up.  This is on firefox 117.0.1 so it seems to not be dependent on the browser used (since OP was using chrome).

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.

**Comment by Riffz** [comment]
This fixed everything on my end.  Thanks so much.
