### ISSUE TITLE
mixing.dj

### ISSUE THREAD

**Issue by NLZ** [AdguardTeam/AdguardFilters#177931]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

n/a

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mixing.dj/slam-slam-radio-593-kameliia-25-04-2024/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. AdGuard Base filter is blocking cloudfront.net on mixing.dj, which is required for music playback. What gives?

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/884277/0a6aaa18-8053-42fe-84cc-d497023533c8)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't see such request. Are additional actions required to reproduce the problem, or is it enough to open the page?

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/2237d832-7b38-4f27-992c-f767baf8d027)



</details>

**Comment by xglossyntx** [comment]
<details>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/149155649/c61b6fb8-73f3-48e1-af1f-dd66992c0581)

**Comment by xglossyntx** [comment]
It only seems to happen when using uBlock Origin; when I use AdGuard, it works fine.

**Comment by xglossyntx** [comment]
It's caused by this rule.

``||cloudfront.net^$domain=porn00.org|milfnut.com|iir.ai|tii.ai|adshort.club|newepisodes.co|megaup.net|ckk.ai|uploadas.com|gounlimited.to|streamtajm.com|yesmovies.to|thehouseofportable.com|kanqite.com|oke.io|xmovies8.pl|xrivonet.info|linkrex.net|youtubemultidownloader.com|cpygames.com|drhtv.com.pl|srt.am|dancingastronaut.com|mixing.dj|gamesofpc.com|tinyical.com|itdmusic.com|prefiles.com|cloudyfiles.co|anime-odcinki.pl|clickndownload.*|clicknupload.*|unblocked.lol|lipstickalley.com|addic7ed.com|animeflv.net|avxhome.in|avxhome.se|baiscopelk.com|filescdn.com|javgo.me|katfile.com|keeplinks.eu|leporno.org|multiup.org|newpct.com|newpct1.com|nhentai.net|nitroflare.com|psarips.com|sadeemapk.com|sankakucomplex.com|shink.in|uplod.it|uplod.ws|uptostream.com|userscloud.com|tmearn.com|y2mate.com|animepahe.ru|tei.ai|mastibaaz.com|mrpcgamer.co|soap2day.*|igg-games.com|torrentmac.net|send.cm|bluemediafiles.*|sakurafile.com|allmoviesforyou.net|soap2day.ac|torrentgalaxy.mx|igg-games.co|ziperto.com|bluemediafile.*|oxtorrent.sk|bluemedialink.online|bluemediaurls.lol|bluemediadownload.*|urlbluemedia.*``

**Comment by Alex-302** [comment]
You can disable CNAME filtering. It is a bad idea to apply it with the rules, which are limited by `$domain`. Not the first case.
But removed this site from the rule.
