### ISSUE TITLE
france24.com

### ISSUE THREAD

**Issue by Broken-Glass1** [AdguardTeam/AdguardFilters#178985]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

Latest version

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.france24.com/en

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

Cookie notice on Samsung browser on Android.

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
This website requires to accept cookie notice, otherwise some elements will not load, related to - https://github.com/AdguardTeam/AdguardFilters/issues/125097
It's fixed by "advanced" rules which are not supported by content blockers.
Please install AdGuard for Android from - https://adguard.com/adguard-android/overview.html
