### ISSUE TITLE
hoodtrendspredict.com

### ISSUE THREAD

**Issue by Khandaker-Atik** [AdguardTeam/AdguardFilters#193612]
### Platform

Android

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

No I don't

### Your configuration

Using Android-14 in Xiaomi Redmi Phone
Browser : Chrome

### Issue Details

I am using private dns option and host : (dns.adguard.com) in my android phone.

There is no other ad blocker in my phone except adguard.
Previously when i went to this website there was no problem but recently when i tried to go this website a prompt / pop up came.

Website: [https://hoodtrendspredict.com/]

A pop up arise "Ads Blocker Detected!!!
We have detected that you are using extensions to block ads. Please support us by disabling these ads blocker. Thank You 🙏
**Powered By chp adblock."**

### Expected Behavior

No popup show as ad blocker detected .

### Actual Behavior

A pop up arise "Ads Blocker Detected!!!
We have detected that you are using extensions to block ads. Please support us by disabling these ads blocker. Thank You 🙏
**Powered By chp adblock."**

### Screenshots

<details><summary>Screenshot 1:</summary>

![SS](https://github.com/user-attachments/assets/94c9f4b2-ebc6-41c8-bbb7-2437a51bc64e)
</details>

**Comment by zloyden** [comment]
If you only use AdGuard DNS, that won't be enough. You can switch to AdGuard Non-filtering DNS or Private DNS and unblock the necessary request there.
However, it was fixed in the filters, so it's best to install [AdGuard for Android](https://adguard.com/adguard-android/overview.html). Update should be available in 2-3 hours.
