### ISSUE TITLE
Shall we remove ||imasdk.googleapis.com^ from filters?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#26607]
Do you know what it is under imasdk.googleapis.com?
Spyware or something?

@ameshkov
@AdamWr

I mean, is it necessary to block it such like blocking google-analytics.com?

You know more and more videos on websites or apps can't be played if blocking the whole imasdk.googleapis.com.

Maybe unblock it?

**Comment by krystian3w** [comment]
Unless so far there were exceptions for specific domains or some simple scripting rules when it made sense to write them.

**Comment by THEtomaso** [comment]
In general, all things Google contains some form of "spyware".
At least if you count their tracking and user data collecting.

That being said, turning all the site-specific exception rules for this particular script into a generic one, would still make sense:
 `imasdk.googleapis.com/js/sdkloader/ima3.js`
Because, like I've pointed out before, blocking that script causes video playback issues on many sites!:
https://github.com/easylist/easylist/issues/1996#issuecomment-437624529

I've actually requested `ima3.js` to be added to '**Decentraleyes**' here:
https://git.synz.io/Synzvato/decentraleyes/issues/326/
..but don't know if it will actually happen.

**Comment by ameshkov** [comment]
The domain is generally ad related and used for this:
https://developers.google.com/interactive-media-ads/

> You know more and more videos on websites or apps can't be played if blocking the whole imasdk.googleapis.com.

Maybe we should do smth like this:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js`
`@@||imasdk.googleapis.com^|` -- to not block it on the DNS-level where you can't deal with such domains.

@AdguardTeam/filters-maintainers guys, you know more about that, plz comment.

**Comment by THEtomaso** [comment]
I must point out that since I've been using '**Decentraleyes**' for a long time, blocking `imasdk.googleapis.com` in general, might cause more problems than I'm currently aware of.

**Comment by lancelot-moon** [comment]
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js` is not enough.

You know apps for Android v7 and above don't trust AG certificate.

Therefore, you had added many such rules.
`@@||imasdk.googleapis.com^$app=xxxxxx`

That's why I think it's better to remove `||imasdk.googleapis.com^`.

**Comment by Alex-302** [comment]
> Maybe we should do smth like this:
> `@@||imasdk.googleapis.com/js/sdkloader/ima3.js`
> `@@||imasdk.googleapis.com^|` -- to not block it on the DNS-level where you can't deal with such domains.

`@@||imasdk.googleapis.com^|` added to SNDS filter.

> `@@||imasdk.googleapis.com/js/sdkloader/ima3.js` - with this exclusion some players does not work, but this rule will not be applied when HTTPS filtering is disabled.
