### ISSUE TITLE
http://www.redmondpie.com/ - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2870]
http://www.redmondpie.com/

<details>
![image12](https://cloud.githubusercontent.com/assets/15856304/17932846/e62dec00-69df-11e6-8069-9ed2726e7225.jpg)
![image1](https://cloud.githubusercontent.com/assets/15856304/17932929/201eff76-69e0-11e6-9896-04e39f6db047.jpg)
</details>
<details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.92.12 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.7.34 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.11.83 Enabled=YES

ID=14 Name="Annoyances filter" Version=1.0.3.1 Enabled=YES

ID=11 Name="Mobile Ads filter" Version=1.0.4.69 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES

ID=110 Name="EasyList Lithuania" Version=1.0.0.86 Enabled=YES

ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES

ID=207 Name="Adblock Warning Removal List" Version=1.0.64.4 Enabled=YES

ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

**Comment by Alex-302** [comment]
1 - it must be hidden. Try:
```
redmondpie.com##div[align="center"][style="padding-bottom:10px;"]
```
2 - I can't find it

**Comment by kaskurkada** [comment]
Can I helo you with replicating the issue or somehow else?

**Comment by Alex-302** [comment]
@kaskurkada try to disable all filters, except English.

**Comment by kaskurkada** [comment]
Still shows white space:

[image: image1.PNG]

On 27 Aug 2016, at 19:03, Alex <notifications@github.com> wrote:

@kaskurkada <https://github.com/kaskurkada> try to disable all filters,
except English.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardFilters/issues/2870#issuecomment-242925422>,
or mute the thread

**Comment by Alex-302** [comment]
Your screenshot is not attached.
Add a direct url of that page.

**Comment by kaskurkada** [comment]
http://www.15min.lt/m

On 27 Aug 2016, at 20:33, Alex <notifications@github.com> wrote:

Your screenshot is not attached.
Add a direct url of that page.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardFilters/issues/2870#issuecomment-242930122>,
or mute the thread

**Comment by Alex-302** [comment]
Nothing.

**Comment by kaskurkada** [comment]
Can't understand anything. Nothing has changed, white space is still
showing in www.redmondpie.com
[image: image1.(null)]

Also if I enter any of articles, this is what I see:

[image: image2.(null)]

On 27 Aug 2016, at 21:08, Alex <notifications@github.com> wrote:

Nothing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardFilters/issues/2870#issuecomment-242931987>,
or mute the thread

**Comment by Alex-302** [comment]
I don't see your screenshots. They are uploaded incorrectly. So I can't find that element.

**Comment by kaskurkada** [comment]
https://i.imgur.com/3JrH2KY.png

**Comment by kaskurkada** [comment]
https://imgur.com/a/pWbz0

**Comment by Alex-302** [comment]
Where the direct url? Is it in articles on on the main page?
Try to disable all filters and add
```
redmondpie.com##div[align="center"][style="padding-bottom:10px;"]
```

**Comment by worldsdream** [comment]
I usually go to http://www.redmondpie.com/
I just checked again and there are no white spaces

iOS 9.3.3, latest stable adguard for iOS
Filters: EN, Dutch, Annoyance, Safari, Mobile

**Comment by kaskurkada** [comment]
Hi! I have checked same filters that you've mentioned and bingo! Now it really works for me. Thank you!
