### ISSUE TITLE
http://www.pornhub.com/ 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2905]
I surf the net using samsung inbuilt browser. Ok now do these steps, first
open the site http://www.pornhub.com/ now click on the videos one by one
and then you will see that after clicking videos one by one, in the
beginning the video player loads but then it won't load. I had to restart
my inbuilt browser after watching one video which is irritating.

I had just checked that If i disable adguard then there is no such problem
of video player loading, so there is problem with adguard, when it is
enabled then video player does not load if you click on videos one by one.

1396854

**Comment by rajatmathurs** [comment]
Well to see the problem enable adguard then clear the catche of Samsung and Google chrome browser now open the site www.pornhub.com when you click on any video then it loads now when i click on other video now the video player does not load. If I click on another videos then video player is not loading too. Now i had to disable adguard and open the site then every video opens and then when I enable adguard then it plays every video too. So this problem happens when you clear the catche.

I had disable filters one by one but it did not work.

Please fix this problem.

Thanks

**Comment by evgeniy-ADG** [comment]
Does toggling HTTPS filtering make change? If you disable all filters but leave the filtering enabled, you're still able to reproduce the issue?

**Comment by rajatmathurs** [comment]
Till yesterday there was the problem but when We I just checked again in chrome there is no problem now

I guess the problem

Thanks for the help issue closed
