### ISSUE TITLE
http://www.spidersweb.pl/ - ads on the main page

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3213]
Windows 10 
Adguard 6.1
Filters
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19479721/c6a09b48-9550-11e6-9a42-f9eff8452792.png)
</details>
Screenshot
<details>
![default](https://cloud.githubusercontent.com/assets/20476168/19479791/1700bb68-9551-11e6-87f1-1959655040e5.PNG)
</details>

**Comment by Alex-302** [comment]
Because "Polskie reguly" is disabled. I don't see this banner with enabled Polish filter.

**Comment by Fridrix** [comment]
@Alex-302 
User still sees ads. Even with polish filter enabled.
ID 1431936

**Comment by Alex-302** [comment]
@Fridrix Did you check it?

**Comment by Fridrix** [comment]
@Alex-302 everithing well on my side

**Comment by Alex-302** [comment]
Maybe user's filters are old. Please ask him for check again.

**Comment by Fridrix** [comment]
@Alex-302 
Here's also ads. Polish and English enabled. Reproduced on my side.
![spidersweb](https://cloud.githubusercontent.com/assets/20476168/19524959/1e579e40-9628-11e6-975d-55a05119a817.jpg)

**Comment by Alex-302** [comment]
Added to English filter
```
spidersweb.pl##.four.columns.pull-right a[rel="nofollow"] > img
```

**Comment by krzysior78** [comment]
Hello.
I'm the one who originally reported this issue.
I would like to additionally inform  that this site is perfectly displayed with no ads when
using Chrome Adguard extension. It looks like there are some differences in filtering engines of Adguard for Windows and Adguard browser extension, because used filtering sets was the same...
Thanks for all support.

**Comment by Alex-302** [comment]
Hi @krzysior78 
Please make a screenshots of ads.

**Comment by krzysior78** [comment]
Hi @Alex-302
I'm attaching 2 screenshots:
First was made with Adguard for Windows enabled, there are 5 ads visible on it.
Second was made with Adguard browser extension, and there are no ads that are visible on first screenshot.
Both was made in Chrome and with the same filter rules sets (English and Polish).
Of course, I could no bother you, and block these ads myself with help of user filter functionality...
But, I would like to point your attention to this issue, because if same filter rules leads to different
webpage display results in both your products, so there could be other webpages which may be
affected in the same way.
Ok, thank you very much for all your efforts.

Adguard for Windows:

![1](https://cloud.githubusercontent.com/assets/22944726/19566065/4e07513c-96e9-11e6-837d-523b85799e71.jpg)

Adguard browser extension:

![2](https://cloud.githubusercontent.com/assets/22944726/19566097/5f581692-96e9-11e6-86f4-04fa8072e8f2.jpg)

**Comment by Alex-302** [comment]
Ok. Confirmed now. I will make additional rules.

**Comment by Alex-302** [comment]
Please check following rule in user filter:
```
spidersweb.pl##body .twelve.columns.hide-for-small.text-center
```

**Comment by krzysior78** [comment]
Please, delete last 2 rules from English filter:
spidersweb.pl##.four.columns.pull-right a[rel="nofollow"] > img
spidersweb.pl##body .twelve.columns.hide-for-small.text-center

and in exchange add this one:
spidersweb.pl##body .text-center

This single one covers all 5 ads, which I've mentioned in last comment.
Basically this rule is modified one from polish filter:
spidersweb.pl##.text-center
which for some reason doesn't work in Adguard for Windows...
Maybe you could check why, so corrections like this wouldn't be necessary in future.
Thank you for your patience :)

**Comment by Alex-302** [comment]
> Please, delete last 2 rules from English filter:
> spidersweb.pl##.four.columns.pull-right a[rel="nofollow"] > img
> spidersweb.pl##body .twelve.columns.hide-for-small.text-center

Removed. But these rules hides the ads. Are you sure that are unnecessary?

> and in exchange add this one:
> spidersweb.pl##body .text-center

with body tag selector has a higher priority, and sometimes rule can hide elements with `display: block!important` attribute

**Comment by krzysior78** [comment]
I'm using this rule since yesterday and everything looks ok on spidersweb.pl. Checked even a moment 
ago, no ads on spidersweb.pl, so this one rule replaces removed ones very well or even better, because with old ones there was still 1 add on page.
By the way, do you know why original rule from polish filter:
`spidersweb.pl##.text-center`
doesn't work in Adguard for Windows?
Thanks.

**Comment by Alex-302** [comment]
> doesn't work in Adguard for Windows?

yes, sometimes element hiding is not working, for example in this case
> with body tag selector has a higher priority, and sometimes rule can hide elements with display: block!important attribute
Adguard for Windows and browser extension has different methods for injecting styles.
