### ISSUE TITLE
Gumtree app - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3310]
https://play.google.com/store/apps/details?id=com.gumtree.android&hl=en
![9vbugjudw9m](https://cloud.githubusercontent.com/assets/15856304/19854357/3beec49e-9f77-11e6-9a83-75fedf3869c7.jpg)

The one on top

<details>
HQ method, English, spyware,  social media, annoyances, Russian, mobile ads, HTTPS

**Comment by jo2dan23** [comment]
Dont see ads on the iphone version one, but there is Tracker 

ingest.crittercism.com

**Comment by jo2dan23** [comment]
Dont see ads on the iphone version one, but there is Tracker 

ingest.crittercism.com

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||gumtree.com/partner/bing?*&adUnitId=
||gumtree.com/partner/bingimpression?
||ingest.crittercism.com
```

**Comment by orgempire** [comment]
why is this close it not been fix yet the filters u add here dont do any think still got that ad on the top on the app on android all so it on the internet web page as well

**Comment by jo2dan23** [comment]
Use fillder to get a log then please. Because i dontnsee any on the iOS version.

**Comment by Alex-302** [comment]
I don't understand you, add commas to your message.

**Comment by orgempire** [comment]
i use the filter don't do any think.i am on android i comment here because it say it been resolved it have not been resolved that why i comment here...i use noroot  firewall app that app block it that ad on the top but that app will block any think it hard to know what to let in and not please resolved this because it not been resolved yet

**Comment by Alex-302** [comment]
@orgempire is HTTPS filtering enabled? Which filtering mode?

**Comment by orgempire** [comment]
@Alex that work i did not have https enabled now it is enabled now it block that ad..thanks for that info..i new to is adguard app any way how come the https is not enabled how come got to turn it...ps thanks again for the help

**Comment by orgempire** [comment]
@Alex that work i did not have https enabled now it is enabled now it block that ad..thanks for that info..i new to is adguard app any way how come the https is not enabled how come got to turn it on...ps thanks again for the help...miss out on in last comment

**Comment by orgempire** [comment]
but now it block my manage ads what i am selling on gumtree i have to turn of https to see my manage ads what i am selling can this be fix or not or do i have to turn of https to see my manage ads all the time

**Comment by Alex-302** [comment]
> it block my manage ads what i am selling on gumtree

could you make screenshots with and without Adguard?

**Comment by orgempire** [comment]
ok with out adguardand with adugard

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Alex <notifications@github.com> Date: 04/11/2016  2:42 p.m.  (GMT+00:00) To: AdguardTeam/AdguardFilters <AdguardFilters@noreply.github.com> Cc: orgempire <jamietuffs76545@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [AdguardTeam/AdguardFilters] Gumtree app - ad (#3310) 

it block my manage ads what i am selling on gumtree


could you make screenshots with and without Adguard?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AdguardTeam/AdguardFilters","title":"AdguardTeam/AdguardFilters","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AdguardTeam/AdguardFilters"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Alex-302 in #3310: \u003e it block my manage ads what i am selling on gumtree\r\n\r\ncould you make screenshots with and without Adguard?"}],"action":{"name":"View Issue","url":"https://github.com/AdguardTeam/AdguardFilters/issues/3310#issuecomment-258449701"}}}

**Comment by Alex-302** [comment]
Please reply from github directly. Your message is absolute unreadable.

**Comment by orgempire** [comment]
![screenshot_20161104-170755](https://cloud.githubusercontent.com/assets/23232531/20033203/9c7f719e-a393-11e6-8a9d-45b13349844e.png)

with out adguard

![screenshot_20161104-170816](https://cloud.githubusercontent.com/assets/23232531/20033206/c2aa1e6e-a393-11e6-807d-2b60fa92736f.png)

with aduard

**Comment by Alex-302** [comment]
Ok, got it.
Added to Mobile filter
```
@@||android-api-de.gumtree.com/api/users/*/ads.json
```
