### ISSUE TITLE
Microsoft Edge Adguard Extension - problem with cookies - please look on one rule fix that.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#33914]
Hello,
Adguard extension in old MS Edge has problem with cookies on dobreprogramy.pl and forum.dobreprogramy.pl
But after add that rule 
||wp.pl/*-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-$script,domain=~pilot.wp.pl
problem fixed. Can you look on that rule and add to filters (can be global on all wp domains).
Best Regards

**Comment by bogachenko** [comment]
`||wp.pl/*-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-$script,domain=~pilot.wp.pl`

`FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs`

this value will change in a few hours.

**Comment by seba2282** [comment]
You said about all rule or only part, where is ID not liked gemius (that value under all rule), @bogachenko?

**Comment by AdamWr** [comment]
This rule is not new, it was added to Polish filter in January - https://github.com/MajkiIT/polish-ads-filter/commit/aeb0cc182d726c516c2f828dcfca526338a82e3e#diff-711027ed0794992ae3b8710d874f3df7R3831 but it was removed later for some reason.
So it seems that it's not changed so often.

Added it for content blockers and Edge extension.

By the way, this cookie notice is fixed by JavaScript rule, but it doesn't work in Edge due to this issue - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1389
