### ISSUE TITLE
bloomberg.com/live/us - player is blocked by Adguard

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3857]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:  
* **Current behaviour**: If you leave the ad blocker ON then the complete streaming of the show is blocked.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](
![screen shot 2016-12-23 at 12 36 17 pm](https://cloud.githubusercontent.com/assets/22892774/21453239/e73a93d8-c915-11e6-997d-c909c772fdb3.png)
)

</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Сhrome
Adguard version: | 1.4.0; 6.1.298.1564
Adguard filters: | 1, 2, 3, 4, 5, 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1472048

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Mrathe** [comment]
Hi,
I'm the one that reported the problem at first. Don't know if that coul be any help but I was able to get around  some of the major pain of the issue. This page is mostly live on my monitor all day and when I open it first I deactivate Adguard. Then The fisrt Bloomberg add comes in (their app mobile presentation - 15 seconds) then I turn Adguard on and all the default filters work fine i.e. present the pauses as stock quotes and music (before, this was partly polluted by videos ads). But the video section provoque an error on the browser after a couple of hours and what I noticed is that it happens when the 1,000 blocked items marks is attained (number attached to the icon on far right). If this is a limit and can be lifted then I'm sure that the behavior would be fine during the day. The only problem remaining is still though that I have to turn it off and on at the beginning. If rules can be permenently made I'd be happy. Also note that I'm using HTTPS eveywhere and Disconnect also in Chrome. Please note that the Bloomberg problem was happening befor I put the las 2 extensions just mentionned. These make the browser quite faster. Thanks.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=bloomberg.com
```
@Mrathe you can add it to user filter and check.

**Comment by Mrathe** [comment]
Hi, Thanks immensly for the quick response.
I add the line and restarted the browser and went directly to the live stream (perfect).
I'll monitor it through the day to see if that rule has sustainability.
Please can you explain me briefly why that particular line is filtering efficiently when this site seems to be involving zillions of requests, adds and stuff. Knowing this I'll be able to apply the reasoning to other sites. Thanks again.

**Comment by Alex-302** [comment]
@Mrathe player uses many ad systems and analytics. Sometimes ad blocking causes an issues like this, so we make partial exclusions.

**Comment by Mrathe** [comment]
Since I add the line everything's fine and the cumulative number of items blocked (icon) seems to have dropped significantly. 

Thank you so much for the help.

Michel
