### ISSUE TITLE
watchfree.to

### ISSUE THREAD

**Issue by uBlock-user** [AdguardTeam/AdguardFilters#4339]
**Description**: A cosmetic filter hides the seasons and episodes list.

**Current behaviour**: 

Season and episode list is hidden on this page - http://www.watchfree.to/watch-29bc93-Arrow-tv-show-online-free-putlocker.html

**Screenshot**:

https://i.gyazo.com/d089d22dbeedfab6d1063f0fd1c55de6.png

**Expected behaviour**: 

Seasons and episodes list would appear.

**Screenshot**:

https://i.gyazo.com/5f243ff9f540a019956a29234da46f76.png

**Steps to reproduce the problem**:

1) Make sure you're subscribed to Adguard English Filter.
2) Browse to http://www.watchfree.to/watch-29bc93-Arrow-tv-show-online-free-putlocker.html

**System configuration** - Chromium 58 with uBO on Windows 10 64 bit and with Adguard English Filter

**PS** - Solution would be to remove this filter - `watchfree.to##.page_content > div[class]:not(.links_left_container):not(.list_links)` from Adguard English Filter

**Comment by uBlock-user** [comment]
@ameshkov Would you ?

**Comment by Alex-302** [comment]
removed
```
watchfree.to##.page_content > div[class]:not(.links_left_container):not(.list_links)
```

**Comment by uBlock-user** [comment]
The filter is still present - https://filters.adtidy.org/extension/chromium/filters/2.txt

Where did you remove it from ?

**Comment by Alex-302** [comment]
You should to wait minimum one hour before checking for updates.

**Comment by uBlock-user** [comment]
Okay, I thought it was instanteous like with uBlock and others.

**Comment by ameshkov** [comment]
@uBlock-user we don't rely on github and serve filters from our own servers. The bright side is that they will never be lost. On the other hand, it is not cheap to serve more than 100TB daily. 

That's why AG has a different way of checking updates. Instead of simply downloading a filter, it first checks the [index file](https://filters.adtidy.org/extension/chromium/filters.json) and downloads only updated filters. Index file must be updated along with the filters files, and it is done on a hourly basis (unless there is an urgent fix).

**Comment by uBlock-user** [comment]
Thanks for the info, Ameshkov.
