### ISSUE TITLE
[Android] Ads in the Unseen app.

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4698]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
ads are not blocked in the app [Unseen](https://play.google.com/store/apps/details?id=com.tda.unseen)
we were not able to reproduce it on our end

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshots:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/24548029/a2fe84d8-161b-11e7-952f-59396372aff4.png)
![image](https://cloud.githubusercontent.com/assets/14153331/24548035/a53d8f82-161b-11e7-8a76-42348b7bc543.png)
![image](https://cloud.githubusercontent.com/assets/14153331/24548040/a99ffa60-161b-11e7-8f91-a7c0deea1b68.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.53
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 14, 10, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists) - 420626; also sent HAR:
https://we.tl/qIiOUTXEEI

**Comment by seanl-adg** [comment]
I couldn't reproduce, and the HAR file seems to be deleted, could you post it again?

**Comment by seanl-adg** [comment]
Ah, got HAR files from the ticket, so nevermind.

**Comment by Alex-302** [comment]
@seanl-adg any news?)

**Comment by seanl-adg** [comment]
I checked out HAR logs attached in https://qcrm.supportyourapp.com/#/customer/420626, specifically files attached in a message received on 23 March and 28 March. One of them contained logs of unblocked ad server `sdk.adincube.com`, and it is blocked in Mobile ads filter since this May by a commit https://github.com/AdguardTeam/AdguardFilters/commit/baaea19ef1788430884a3634e69b815c07528f33 after a report about a different app.
Other than this, I couldn't find something that could be a cause of ads in har logs.

If the user is still expriencing issues, this could be an issue of Adguard app itself.

**Comment by Alex-302** [comment]
@deLumren Please check again.
