### ISSUE TITLE
LA Times articles do not load with a scroll bar

### ISSUE THREAD

**Issue by kayakerr** [AdguardTeam/AdguardFilters#46993]
When adguard is on with all of the filters enabled, all articles on the LA Times website are missing the scrollbar leaving me unable to read the article (and wont even scroll when using the keyboard arrows). Turning adguard off fixes this  problem.

I recently enabled the "annoyances" filter so I think this has something to do with it.

It happens on articles on the LA Times website, like this one https://www.latimes.com/california/story/2020-01-02/california-snowpack-measurement-2020-boosted-recent-storms

**Comment by BlazDT** [comment]
Not reproduced on my Windows. Please list required information as outlined in template.

**Comment by kayakerr** [comment]
I am not sure what template to use - I clicked on the manual report instructions in the extension since the report feature is also broken.

**Comment by BlazDT** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/new?template=Ad_report.md

Not reproduced on Chrome Extension.

**Comment by kayakerr** [comment]
Ok will see if I can fill all that out. 

I can reproduce on all of my windows machines with the chrome extension. You have to click on 5 or 6 articles before it happens (i assume it has something to do with the paywall popup that is being blocked by the ext)

**Comment by BlazDT** [comment]
Checked different articles, scrolling still works. Please check @AdamWr

**Comment by AdamWr** [comment]
I guess one of filters is blocking paywall overlay.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/71719747-9365af00-2e1f-11ea-8f52-2bdd083732fe.png)

</details>

As I see, it may be caused by this rule `###reg-overlay` from `Web Annoyances Ultralist`.
But maybe it's caused by other filters too, so we need to know which exactly filters do you use.

By the way, it's a paywall, so we will not fix it in our filters, but to unblock scroll you can add these rules to user filter:
```
latimes.com#%#window.addEventListener("scroll",function(a){a.stopPropagation()},!0);
latimes.com#$#html[data-dss-meterup] { overflow: visible!important; }
latimes.com#$#html[data-dss-meterup] > body { overflow: visible!important; }
```

**Comment by krystian3w** [comment]
@yourduskquibbles?
