### ISSUE TITLE
incorrect blocking with French filter https://sovereignmanconfidential.com/index

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5260]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
incorrect blocking with French filter
https://sovereignmanconfidential.com/index

* **Current behaviour**: 
with Adguard
<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26771748/b86be932-49c9-11e7-97e4-869422472a9f.png)

</details>

without Adg
<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26771773/e39e0ec8-49c9-11e7-9a5b-6c21831f3fae.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): |  TDI
Stealth mode options(Windows) | none
Adguard filters: | rus, eng, French, annoyance, social, spyware, mobile, experimental
Ticket ID (if exists): | 1568157

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to French filter
```
@@||clickfunnels.com^$domain=sovereignmanconfidential.com
```

**Comment by KimchaC** [comment]
Hi,

I am the original person who reported this problem. Thanks for making this a priority and fixing it so quickly.

Unfortunately this only resolves the problem for this specific case. 

This page is built using a webpage builder called Clickfunnels. They have hundreds (maybe thousands) of customers on various domains and all of these will continue to be broken.

We have content on two more domains that would still be affected for example.

For us, can you please add the following domains to the exception:
- http://sovereignacademy.org/blacksmithcamp
- https://join.sovereignman.com/smc12m_nnf_main_banking

But preferably, I would like to see the actual root cause of the pages being broken removed.

Thanks for all your efforts and super quick support response. I was really impressed by that.

Greetings, Kim

**Comment by Alex-302** [comment]
Hi
I don't see the blocking rule in French and Liste FR filters. Maybe it was removed.
Please check again after filters update.

**Comment by KimchaC** [comment]
Thanks, looks like it's working for me now.

**Comment by Alex-302** [comment]
Ok)
