### ISSUE TITLE
missed ad Alyac android app

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5263]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ad Alyac android app
https://play.google.com/store/apps/details?id=com.estsoft.alyac&hl=en

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26778558/6f6ce6e8-49ea-11e7-8204-25a0401d41e0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.111
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | eng, rus, annoyance, spyware, social, experimental, mobile, Korean Adblock, List-KR
Ticket ID (if exists): | 1569592

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
If adblocking is disabled, banners from third-party adservers are displayed in the place shown in the screenshot.
The banner currently being displayed with Adguard enabled is a default banner which is being shown when third-party adserver is unavailable (because it is blocked by Adguard).
It even appear when an internet connection is disabled. We can't hide it in such cases.
