### ISSUE TITLE
miniminiplus.pl - ads by redcdn.pl

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5558]
**seba2282** commented:
>I have a question about Firefox Android. Why Adguard, Ublock Origin or etc not block blocking video ads by redcdn.pl domain on example miniminiplus.pl ? I see all time big popup with this video ads. Is it bug in Firefox or in blockers ? Sorry my question.

>Ok. You need Firefox Android + Adguard extension. Reek filter and acceptable ads disabled, all filters activated. And testing miniminiplus.pl/filmy . After few time you will see big popup ads video.

>Few films video maybe any problem but after...

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by seba2282** [comment]
Sorry for my big longtime not activity. I had a problem with pc and smartphone. I tried this combinations, what I wrote and I see fixed problem, but FF for Android actually is unusuable, because works slow. And I must use chrome + AG apk. I fixed problem with miniminiplus.pl as use two rules @@||tvn.adocean.pl and @@||s1-player5.cdntvn.pl . The same rules work with ms edge + ag extension. But teletoonplus.pl base the same rules and AG detects by site and videos are blocking. 
One more sorry. But I can't write longtime.

**Comment by Alex-302** [comment]
Do you use DNS filtering?

**Comment by seba2282** [comment]
Yes. It is basic from my options. Without this option or extension browsers (here I didn't see DNS filter) I have the same problem (PC MS Edge, Android).

**Comment by Alex-302** [comment]
It works fine on all my devices without DNS filtering.

**Comment by seba2282** [comment]
Try link teletoonplus.pl/filmy and watch some video. I have detecting Adblocker. miniminiplus.pl/filmy working great.

**Comment by seba2282** [comment]
@Alex-302 look here :
https://www.teletoonplus.pl/filmy/z/my-little-pony-equestria-girls
It is example. (Edge + extension) The same I have on Android (chrome + adguard apk with/without DNS Filtering). 
![blocked](https://user-images.githubusercontent.com/16944478/27986525-30b76984-6400-11e7-98dc-6ebf4262cc3f.PNG)
