### ISSUE TITLE
[Content Blocker] https://www.apkmirror.com/ - missed placeholders, Samsung Internet only

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6594]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Works fine in Yandex, here's the link: https://www.apkmirror.com/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30004273-d515cbc8-90d4-11e7-87fa-673485674fce.png)

</details><br/>

***System configuration***

**Filters:**

English, Social media, Useful ads, Experimental, Mobile ads, EasyList Italy, Reek

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | Samsung Internet
AdGuard version:                    | 1.7.0
Helpdesk ID (if exists):            | 1142913

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.

**Comment by evgeniy-ADG** [comment]
The customer says it didn't help, uses the English filter, updated on September 5th.

**Comment by AdamWr** [comment]
Unfortunately we can't hide all ad leftovers on this page, with AdGuard Content Blocker, because website detects ad blockers.

<details><summary>Screenshot</summary>

![screenshot_2017-09-07-15-09-54](https://user-images.githubusercontent.com/29142494/30165041-dc202a0a-93de-11e7-98c9-b0ed4cfc765b.png)

</details>
<br>

I checked it with AdGuard for Android with disabled JS rules and ad leftover on main page should be hidden by this rule:
`apkmirror.com##.google-ad-leaderboard`

**Comment by Alex-302** [comment]
Ad block detection will trigger if we hide it.
