### ISSUE TITLE
Не блокирует рекламу

### ISSUE THREAD

**Issue by it0mac** [AdguardTeam/AdguardFilters#66790]
Браузерное расширение Adguard 3.5.20. Фильтры обновлены. Браузер: Chrome. На странице: https://www.twitch.tv/ybicanoooobov
![image](https://user-images.githubusercontent.com/72110364/97816948-f3c4b780-1ca1-11eb-9f00-09f298995c28.png)
Плюс ко всему, обратная связь не работает, так как не пускает дальше этого пункта:
![image](https://user-images.githubusercontent.com/72110364/97816976-1c4cb180-1ca2-11eb-91cc-0df669bf6186.png)

**Comment by rubrodapa** [comment]
This has also happen to me and more people that are discussing it on Reddit.

***Description***:
* **Current behaviour**: 

A screen appear saying that a third party tool or browser extension is impacting twitch.tv performance (Dueing the first hours when this issue appeared it showed another screen saying that an commercial break was going on). A few thins I noticed:
- The issue did not appear directly when I enter to a live channel (wich is when twitch usually plays ads)
- This screen appeared during the stream without the streamer placing any ad on the stream. The streamer said specifically he was not running any ads, and other viewers with no adblocks said they didn't see that screen.

<details><summary>Screenshots:</summary>

This is the screen that appears now during 30 seconds (it seems to be 2 "ads" of 15 seconds each but no ad is actually played, the original stream moves to the upper right corner with no audio):

![twitch-2](https://user-images.githubusercontent.com/3008433/97819065-8e26fa00-1ca6-11eb-8da7-b35ac8d33761.png)

The next screen appeared to me the first hours when the issue started to occur (the original stream dissapear for 2 "ads" of 15 seconds each, but no ad is actually played). It hasn't show anymore to me since yesterday (and before the other screen started to show up):

![twitch-comercial](https://user-images.githubusercontent.com/3008433/97819027-5029d600-1ca6-11eb-9f38-a82ce4da5920.png)

</details>

* **Expected behaviour**:

No interruption on stream

Information | Value
-- | --
Operating system: | Windows 10
Browser: | Opera GX
AdGuard version: | AdGuard for Windows 7.5.2. Opera has AdGuard Extension Installed.
Filters enabled: | Adguard Base Filter 2.1.48.34 <br> AdGuard Tracking Protection Filter 2.0.17.99<br>Adguard Social media filter 2.0.32.19 <br> AdGuard Annoyances Filter 2.0.62.35<br>Adblock Warning Removal List 2.0.72.34 <br> Adguard Spanish/Portuguese filter 2.0.7.48
AdGuard DNS: | None
Stealth mode options (Windows only) | No

I hope this could help in fixing this annoying issue. If you need some extra info let me know.

**Comment by Alex-302** [comment]
уже есть про твитч задача: https://github.com/AdguardTeam/AdguardFilters/issues/64754 Лучше туда дописывать.
У меня не повторяется реклама.
