### ISSUE TITLE
Dunkin' Donuts app does not load locations

### ISSUE THREAD

**Issue by Son-Vegitto** [AdguardTeam/AdguardFilters#71189]
Hello,

I'm a beta tester on Android 8.1. I just tried to load the Dunkin' Donuts app, which loaded; however, on the location selection page, I receive a loading error, unless I turn adguard off for the application. 

Please let me know what other info should be included and I will follow up.

**Comment by seyoon20087** [comment]
What version of Adguard for Android app you're using?

We need to know what version of your Adguard for Android is.

**Comment by Son-Vegitto** [comment]
I am using this one: v3.6 (1-1.7.151cl)

**Comment by seyoon20087** [comment]
Please consider the following:

- Check for filter updates on AdGuard app
- Check for system updates on your Android device's preferences

**Dunkin' Donuts app has not been updated after the last update on May 5, 2016, and is removed from the Play Store since it's no longer updated. If you would like to get the latest update of the Dunkin' Dounts app, you can find it [here](https://apkcombo.com/dunkin-donuts/com.skcc.corfire.dd). However, that app is deprecated and Dunkin' Brands, Inc., Dunkin' Donuts, and AdGuard will no longer help you with ongoing issues with the app, so we recommend that you browse Dunkin' Donuts through the [Web](https://www.dunkindonuts.com) instead.**

P.S.: Currently, only [Dunkin' Emojis](https://play.google.com/store/apps/details?id=com.dunkinbrands.emojikeyboard) app is left in the Google Play Store from Dunkin' Brand, Inc.

**Comment by Son-Vegitto** [comment]
Sorry, I may be a bit confused, but the Dunkin' app does not seem to be depreciated. 

https://play.google.com/store/apps/details?id=com.dunkinbrands.otgo

07-Dec-2020 was the latest update of the app. It is still in the Google play store. 

I did ensure that everything is up to date on my end (AdGuard filters and my mobile).

**Comment by Alex-302** [comment]
@Son-Vegitto Hi. Could you please check with disabled filters, DNS filtering, but with enabled protection?

**Comment by Alex-302** [comment]
> to disable all filters under Content Blocking

yes

> ensure DNS filtering is enabled

no, disable DNS filtering. But general AdGuard protection must be enabled.

> Any particular settings under App Management (Firewall)?

No, leave it as is. But if previous changes does not help, please try to disable HTTPS filtering for this app in Apps Management.

**Comment by Alex-302** [comment]
@Son-Vegitto Hi. Any news?)
