### ISSUE TITLE
http://wiadomosci.onet.pl/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7218]
The site is using an anti-adblocker

### Steps to reproduce

1. Go to http://wiadomosci.onet.pl/kraj/ranking-najlepsi-dostawcy-gazu-ziemnego-2017/51beq85
2. See what's on the screenshot below

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32041164-c314423e-ba3b-11e7-94b9-054ba0f7a5dc.png)

</details>

### Customer ID 1650654
Check the support ticket for logs

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by AdamWr** [comment]
This anti adblock notice shouldn't appear with only AdGuard app and with Polish filter list (`Adblock & uBlock polish filter`), but it can happens when AdGuard Extension is installed (even in integration mode), because of this issue - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/860
Fixed.
