### ISSUE TITLE
voltimum.com.tr

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#72290]
1-Ad
https://www.voltimum.com.tr/
<details><summary>Image</summary>

 
![www voltimum com tr](https://user-images.githubusercontent.com/74098460/104715371-86b8ae00-5737-11eb-9b0e-ed5f4ebf3039.png)

</details>

---

2-Ad server

https://www.voltimum.com.tr/haberler/hastanelerde-yangin-guvenligi

<details><summary>Image</summary>

 
![www voltimum com tr (3)](https://user-images.githubusercontent.com/74098460/104715648-dc8d5600-5737-11eb-869d-90651cac0017.png)

</details>

---

3-Incorrect Blocking

https://www.voltimum.com.tr/
<details><summary>Image</summary>

 
![1](https://user-images.githubusercontent.com/74098460/104715769-02b2f600-5738-11eb-814c-8aad8188b4db.png)

</details>

---

```

Filters: Base-Tracking Protection-Social-Annoyance-Turkish 
Browser: Chrome 87  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by THEtomaso** [comment]
@Alex-302:

Perhaps `~fetcherx.com` too?

Example:
`https://fetcherx.com/social/tumblr/stumong/`

..or `fetcherx.com#@#.social-block` instead, since the blocking rule also exists in '**EasyList – Social Widgets**':
https://github.com/easylist/easylist/blob/4c82b9505a6f0246d57c48d60fef0c0366ffc61d/fanboy-addon/fanboy_social_general_hide.txt#L9152

**Comment by Alex-302** [comment]
@THEtomaso Fixed
