### ISSUE TITLE
104找工作 - 找工作 找打工 找兼差 app issue

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#7763]
Today, I tried 104 app.
Android version:
https://play.google.com/store/apps/details?id=com.m104&hl=zh_TW

If enabling AdGuard for Android, there is no the under ad banner on 104 app.
Other features on 104 app is normal.
But it only has the problem in one place (mark with the orange frame).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/go6mqPH.jpg)
</details><br/>

If I enter there, it shows, "The server lost its consciousness, please refresh, thanks. (E500)"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iVM2xHe.png)
</details><br/>

Afterwards, I disabled Mobile ads filter.
But I still was unable to visit that place on 104 app because it's also blocked by English filter's rules.
It's useless even I added m.104.com.tw in the whitelist.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/wbH2eXL.png)
</details><br/>

The URLs were blocked by English filter's rules.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/2wVgFWO.png)

![image](https://i.imgur.com/Z0Ytn5W.png)
</details><br/>

Only enable Mobile ads filter and disable all other filters.
There, it still shows, "The server lost its consciousness, please refresh, thanks. (E500)"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/U4fVlAR.png)
</details><br/>

Finally, I added "@@||m.104.com.tw/api/1.0^" in my user filter.
Those URLs were not blocked by English filter or Mobile ads filter. 
Everything was fine, but the under ad banner appeared.
Do you have other solutions or rules to block ads under the path "m.104.com.tw/api/1.0/ad/" and let me normally visit it?

**Comment by zebrum** [comment]
from [here](https://github.com/AdguardTeam/AdguardForiOS/issues/496#issuecomment-345185388)

**Comment by lancelot-moon** [comment]
@Alex-302 

Hi,

I have solved the issue by myself!

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/J321AWA.jpg)
</details><br/>

The ad banner is caused by these paths:
m.104.com.tw/api/1.0/ad/index_get_new.php
m.104.com.tw/api/1.0/ad/index_get_new_1.php
m.104.com.tw/api/1.0/ad/index_get_new_2.php

Those paths can be blocked by the rule syntax "ad/index" of English filter.
But it results in the problem in one place (mark with the orange frame).
I can't enter enter the place of "通知我的公司".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/go6mqPH.jpg)
</details><br/>

If I try to enter there, it shows, "The server lost its consciousness, please refresh, thanks. (E500)"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iVM2xHe.png)
</details><br/>

It's because that English filter also blocks m.104.com.tw/api/1.0/ad/video_ad_get.php.

I disabled ALL ad filters.
Only enable my user filter.
I added these rules in my user filter:
@@||m.104.com.tw/api/1.0/ad/video_ad_get.php^
||m.104.com.tw/api/1.0/ad/index_get_new.php
||m.104.com.tw/api/1.0/ad/index_get_new_1.php
||m.104.com.tw/api/1.0/ad/index_get_new_2.php

No Ad banner, too.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/6bt4tZF.jpg)
</details><br/>

I already can enter the place of "通知我的公司".
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/tPncCP5.png)
</details><br/>

I only enabled Mobile ads filter for the test. (Other filters and user filter were disabled.)
This link is my log at that time.
https://app.box.com/s/kgyrsn2igp26o9373n01vtvnftrnljbt

1. Please remove "||m.104.com.tw/api/1.0/ad^$app=com.m104" from Mobile ads filter.
I saw that ameshkov added ||m.104.com.tw/api/1.0/ad^$app=com.m104 in Mobile ads filter.
I really feel sorry!
https://github.com/AdguardTeam/AdguardFilters/commit/6d594bd80dd93a3da0f4195b974feada28862588

This rule "||m.104.com.tw/api/1.0/ad^$app=com.m104" blocks "m.104.com.tw/api/1.0/ad/video_ad_get.php", which results in being unable to enter the place of "通知我的公司".

2. Please add @@||m.104.com.tw/api/1.0/ad/video_ad_get.php^ in English filter.
According to the rule syntax "ad/index" of English filter, English filter blocked m.104.com.tw/api/1.0/ad/video_ad_get.php.

We must exclude it from English filter.

3.  Please add the 3 rules in Mobile ads filter.
||m.104.com.tw/api/1.0/ad/index_get_new.php
||m.104.com.tw/api/1.0/ad/index_get_new_1.php
||m.104.com.tw/api/1.0/ad/index_get_new_2.php

Thanks a lot!

**Comment by Alex-302** [comment]
Thanks, added
```
@@||m.104.com.tw/api/1.0/ad/video_ad_get.php$app=com.m104
```
Why we need exclusion in English filter?

**Comment by lancelot-moon** [comment]
If only enabling English filter, English filter also blocks "m.104.com.tw/api/1.0/ad/video_ad_get.php".
I still can't enter the place of "通知我的公司" (The company which contacted with me).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/go6mqPH.jpg)
</details><br/>

If I try to enter there, it shows, "The server lost its consciousness, please refresh, thanks. (E500)"
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iVM2xHe.png)
</details><br/>

So please also add "@@||m.104.com.tw/api/1.0/ad/video_ad_get.php$app=com.m104" in English filter.

**Comment by Alex-302** [comment]
> If only enabling English filter, English filter also blocks "m.104.com.tw/api/1.0/ad/video_ad_get.php".
> "m.104.com.tw/api/1.0/ad/video_ad_get.php" is blocked

Mobile filter is required for mobile devices.

**Comment by lancelot-moon** [comment]
Not everyone knows to enable Mobile ads filter.
Maybe someone only enables English filter and other default filter, except for Mobile ads filter.
If you don't add "@@||m.104.com.tw/api/1.0/ad/video_ad_get.php$app=com.m104" in English filter, he is unable to enter the place of "通知我的公司"(The company which contacted with me) in 104 app.

**Comment by Alex-302** [comment]
It is enabled by default on mobile devices.
