### ISSUE TITLE
add filter lists

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#80179]
bad IPs and domains list:
https://github.com/stamparm/ipsum/blob/master/levels/4.txt
https://github.com/stamparm/blackbook/blob/master/blackbook.txt

**Comment by DandelionSprout** [comment]
1) This kind of request is more suited for https://github.com/AdguardTeam/FiltersRegistry/issues; although you are perfectly forgiven for the mistake, considering AdGuard has ~40 GitHub repos.
2) The first one of those 2 lists would have to be converted (presumably by the AdGuard team) into `$network` in order to work optimally on AdGuard for Windows/Mac/Android.
