### ISSUE TITLE
Add "withAds" and "show_in_content_ads" to the AdGuard URL Tracking filter

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#82109]
> For your tracking parameters URL filter: if you add withAds that will kill ads on Reddit. If you add show_in_content_ads that will kill ads on Yelp.

Reported by: user 506152

**Comment by DandelionSprout** [comment]
[citation needed]

**Comment by DandelionSprout** [comment]
Okay, so it turns out that `withAds` is specific to `https://new.reddit.com/r/popular/`, and that `$removeparam=withAds` fails to actually remove any ads.

I can't find any sources on `show_in_content_ads`, except for an issue report in the AdGuard for Android issue tracker: https://github.com/AdguardTeam/AdguardForAndroid/issues/3773

**Comment by Alex-302** [comment]
I don't see `withAds` parameter in requests.
