### ISSUE TITLE
telerium

### ISSUE THREAD

**Issue by goatgitt** [AdguardTeam/AdguardFilters#83590]
hi,
The telerium filters are killing the adblocker;
When you want to go to telerium, you can see that "The stream is offline",
but, if you disable the telerium block script, you can see that the stream is here.
I think that we have to enable a telerium script wich aims at a telerium domain.
Could you fix it please?

**Comment by goatgitt** [comment]
Ok, 
you have to delete this line:
$third-party,xmlhttprequest,domain=telerium.club|telerium.tv|teleriumtv.net

**Comment by krystian3w** [comment]
Made by smed79 or by AdGuard team?

https://github.com/AdguardTeam/AdguardFilters/search?q=%24third-party%2Cxmlhttprequest%2Cdomain%3Dtelerium.club%7Ctelerium.tv%7Cteleriumtv.net&type=commits = 0 match

**Comment by goatgitt** [comment]
> Made by smed79 or by AdGuard team?
> 
> https://github.com/AdguardTeam/AdguardFilters/search?q=%24third-party%2Cxmlhttprequest%2Cdomain%3Dtelerium.club%7Ctelerium.tv%7Cteleriumtv.net&type=commits = 0 match

I am talking about the "FRA:adguard list" into ublock, am I at the good place for it?

**Comment by krystian3w** [comment]
Good but smed79 maybe can reproduce breakge then use ABP, if filter is good for ABP then AdGuard team need add something like:

` $third-party,xmlhttprequest,domain=telerium.club|telerium.tv|teleriumtv.net,badfilter`

or

`@@*$third-party,xmlhttprequest,domain=telerium.club|telerium.tv|teleriumtv.net`

**Comment by goatgitt** [comment]
you have to add something like:
$third-party,xmlhttprequest,domain= others website| !|telerium.club|telerium.tv|teleriumtv.net

**Comment by goatgitt** [comment]
![image](https://user-images.githubusercontent.com/75272099/118943773-3dca6d80-b954-11eb-9d78-1720e2731525.png)

**Comment by krystian3w** [comment]
OK, I found this in origin "liste_fr" mainted by smed79, so this can be fixed in 3 places:

- by smed79 on liste_fr project (if marked as worth unlock a few streams)
- by AdGuard team in linked "whitelist.txt"
- by uAssets team after few weeks then cannot reporoduce broken streams by smed79 and/or AdGuardTeam

---

The best will be generate small allow `third-party` XHR's like:

`@@||example.org^$xmlhttprequest,domain=telerium.club|telerium.tv|teleriumtv.net`
`@@||example.com^$xmlhttprequest,domain=telerium.club|telerium.tv|teleriumtv.net`

to avoid load ads / crypto mainers / tracking.

**Comment by goatgitt** [comment]
These new filters work very well,
the stream don't show the offline message.

**Comment by Alex-302** [comment]
@goatgitt Please describe steps to reproduce.
