### ISSUE TITLE
google.com 

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#87920]
google.com when I write example in search "cosik" and click that link: https://pl.m.wiktionary.org/wiki/cosik then:

with filter Adguard url protect tracking have that 
![Screenshot_2021-07-08-23-04-35.png](https://user-images.githubusercontent.com/16944478/124991471-01f18180-e042-11eb-9911-bd93793a5486.png)

When filter url protect tracking is turned off, then normally go on site 

![Screenshot_2021-07-08-23-05-20.png](https://user-images.githubusercontent.com/16944478/124991571-23526d80-e042-11eb-9a70-b1626472ebab.png)

with www google.pl any problems.

I see actually that in Firefox on Android. I don't know how is with PC because I didn't test

**Comment by krystian3w** [comment]
I see this and may help:

https://addons.mozilla.org/pl/android/addon/google-search-fixer/

**Comment by krystian3w** [comment]
For uBO 1.36.0+ works:

```
@@||google.*/url?q=*&ved=*&usg=*$queryprune,domain=google.*
```

**Comment by seba2282** [comment]
> For uBO 1.36.0+ works:
> 
> ```
> @@||google.*/url?q=*&ved=*&usg=*$queryprune,domain=google.*
> ```

It work, @krystian3w

**Comment by krystian3w** [comment]
@Alex-302 / @AdamWr  / @Sergey-Lyapin / @BlazDT / @Yuki2718 / @zloyden  may need revert remove ved:

https://github.com/AdguardTeam/AdguardFilters/blob/d31f529e8c49fd1879441d6d0300c29593a6b902/TrackParamFilter/sections/specific.txt#L41

**Comment by BlazDT** [comment]
Thank you. Disabled that two.

**Comment by garry-ut99** [comment]
> Alex-302 : https://github.com/AdguardTeam/AdguardFilters/commit/293a7d939039c76b0a24cbcfb7e326108442da4c#r53256922 : Why disabled? I can't reproduce this issue?
> Alex-302 : https://github.com/AdguardTeam/AdguardFilters/commit/293a7d939039c76b0a24cbcfb7e326108442da4c#r53288717 : I don't see any issues with this rule.

I can still reproduce on Mobile after you bringed back the rule in https://github.com/AdguardTeam/AdguardFilters/commit/fe5a4d28af8eebaa43fcf306869459933bb3c71b, 
also another your rule causes it too: https://github.com/AdguardTeam/AdguardFilters/commit/2d1ca8918d2fa74532cd6fa7be6bc9f3e7f26bea , these filters cause it:
`||google.*/search$removeparam=ved`
`||google.*/search$removeparam=sa`

Also see this thread: https://support.mozilla.org/en-US/questions/1279559

<hr>

> seba2282 : https://github.com/AdguardTeam/AdguardFilters/issues/87920#issuecomment-876824022 : 
> > For uBO 1.36.0+ works:
> > ```
> > `@@||google.*/url?q=*&ved=*&usg=*$queryprune,domain=google.*`
> > ```
> It work.

Works for me too, but I've fine-tuned it a bit:
`@@||google.*/url?q=*&sa=*&ved=*&usg=*$removeparam,domain=google.*`
I will see how it works in a long term, because it need to be tested whether all the 3 params are always present together, if not then will need to split the filter into 2 or 3 separate filtes or convert to a regex rule.

**Comment by seba2282** [comment]
Good know that :)

**Comment by Alex-302** [comment]
@garry-ut99 I don't see any problems.
Please write steps to reproduce (better sent a new report using feedback menu in AdGuard - all your settings will be loaded).

**Comment by garry-ut99** [comment]
On Firefox Mobile + AdGuard Browser Ext or uBlock Origin + AdGuard URL Tracking Protection list enabled :
1. Search some phrases in Google search, for example: "wallpapers" or "car photos"
2. Then click some links in the results, for example: "www.pexels.com" or "pixabay.com"
3. Notice you're landing on Google redirect page with "Redirect warning"

The issue doesn't appear on all links, but on some of them, sometimes even every 2nd or 3rd link - depends on a phrase, averagely often enought to be considered a big annoyance, so either a whiltelist should be added, or a scriptlet to defuse Google link scanner script.

I couldn't reproduce with Responsive Design Mode, only on a real smartphone, seems Google scripts are good in distinguishing between a real device and a simulation.

**Comment by Alex-302** [comment]
Can't reproduce. Not sure if it's necessary to change the filters.

**Comment by garry-ut99** [comment]
This f...ing "can't reproduce" / I don't see problems" is quite annoying.
Ok, what is your device / user-agent you are unable to reproduce on, 
I'm asking because the reproducibility depends on it, just like in the initial comment : 

> seba2282 : I see actually that in Firefox on Android. I don't know how is with PC because I didn't test

It can be reproduced only on Android real smartphone, neither in iPhone/iPad, nor in Firefox Responsive Design Mode (which sets some unusual / odd user-agents), (unless manually changed/forced a different user-agent) and even in Android sometimes not reproduce on some user-agent string. 

Example device/user-agent string I can reproduce on:
`Mozilla/5.0 (Android 13; Mobile; rv:122.0) Gecko/122.0 Firefox/122.0`

**Comment by Alex-302** [comment]
> It can be reproduced only on Android real smartphone, neither in iPhone/iPad, nor in Firefox Responsive Design Mode (which sets some unusual / odd user-agents), (unless manually changed/forced a different user-agent) and even in Android sometimes not reproduce on some user-agent string.

I don't use emulation mode, only real devices.

> This f...ing "can't reproduce" / I don't see problems" is quite annoying.
> Ok, what is your device / user-agent you are unable to reproduce on,

You're not the only Firefox Mobile user with a browser extension. There are no other complaints. I assume that the problem is also related to some browser settings. I have two Android devices, and all good.

**Comment by garry-ut99** [comment]
> You're not the only Firefox Mobile user with a browser extension. There are no other complaints. 

Crappy answer, as if you were blind and didn't notice that OP reported same issue (just with a different phrase put in Google search and a different link) and BlazDT fixed it for OP, because BlazDT noticed the issue,  but you didn't see any problem and added the filters again, and now you bringed the issue back for me, and you're saying again you don't see any problem.

> I have two Android devices, and all good.

What does this shitty answer "all good" mean?
Did you try to reproduce on my `user-agent` string or not?

> I assume that the problem is also related to some browser settings. 

Yes, like I already said: related to `user-agent` string. 

Could you be more helpful in reproducing the issue..., I provided you my `user-agent` string in my previous comment, because I expected you to copy it and set the same `user-agent` in your browser and tell me whether you can reproduce the issue with my `user-agent `. Also I asked you what is your device/`user-agent` so that I can check whether I can reproduce the issue on my end with your `user-agent` string. 

Custom `user-agent` string can be set in https://firefox-source-docs.mozilla.org/devtools-user/responsive_design_mode/ or alternatively can use one of plenty extensions in Firefox Desktop to set custom `user-agent`, for example https://addons.mozilla.org/pl/firefox/addon/uaswitcher/ , I don't see any extension for Firefox Mobile, but the issue can be reproduced on Firefox Desktop with custom `user-agent` string anyway.
