### ISSUE TITLE
Winfuture.de - to block or not to block [Annoyances]

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardFilters#88710]
@Morku
@Andy-Kl

Should we block elements like these in Annoyances filter for winfuture.de (see screenshots)?

<img width="518" alt="1" src="https://user-images.githubusercontent.com/34266271/126374898-641e58f2-b12a-4945-9788-c0d5e89b4c51.PNG">
<img width="507" alt="2" src="https://user-images.githubusercontent.com/34266271/126374905-a52f032d-7be4-43a0-9253-ecb512a799b7.PNG">
<img width="503" alt="3" src="https://user-images.githubusercontent.com/34266271/126374907-929c2dbf-a9eb-48ea-99b3-f730eb61ef2d.PNG">
<img width="348" alt="4" src="https://user-images.githubusercontent.com/34266271/126374909-9b0a53a0-89b5-475c-871a-fb123555a203.PNG">

**Comment by Andy-Kl** [comment]
I think no - it is more information than advertising

**Comment by Morku** [comment]
Do you have an example rule to test? Is it even possible to sort out this kind of Shop Ads?

It's indeed not an easy decision. The 1&1 article sounds like a news, combined with affiliate links (but I can't check, if 1&1 REALLY brings back a monthly contract).

Anyway, the Media-Markt and Saturn "Bang-Deals" and "Last Chance" are pure clickbait. Its EVERY WEEK a "last chance".

So personally I tend to yes for Annoyance.

**Comment by Morku** [comment]
After checking the page a little more in detail and since I subscribed their RSS feed, this is what I think:

They always recycle the Media Markt and Saturn offers, tarned as a news, but linking (currently?) to the same article:

- 20.07.2021 16:10 https://winfuture.de/: Letzte Chance: Die günstigen Saturn Jubiläums-Deals enden 20 Uhr -> https://winfuture.de/news,124155.html
- 18.07.2021 10:20 https://winfuture.de/index-3.html: Nur heute: Media Markt und Saturn mit neuen Super-Sonntag-Deals -> https://winfuture.de/news,124155.html
- 16.07.2021 11:16 https://winfuture.de/index-5.html: Nur für 2 Tage: Media Markt und Saturn starten neue Knaller-Deals -> https://winfuture.de/news,124155.html
- 15.07.2021 09:52 https://winfuture.de/index-7.html: Nur für 3 Tage: Günstige Technik-Angebote bei Media Markt & Saturn -> https://winfuture.de/news,124155.html

It's also always typical for this "news", that comments are disabled. Seems like they got tired of clickbait Ads comments ;)

I would greet this to see it blocked in Annoyance filter. But it seems, it might change from time to time, regarding to the searchresult: https://winfuture.de/suche/?q=saturn#gsc.tab=0&gsc.q=saturn

Then, they also advert frequently Notebooksbiller and Amazon Deals:

- 19.07.2021 06:08 Uhr Notebooksbilliger: Angebote der Woche stark reduziert https://winfuture.de/index-3.html -> https://winfuture.de/special/notebooksbilliger/angebote
- https://winfuture.de/special/amazon/angebote/

Would be also nice to see in Annoyance.

The 1&1 "Ad" seems to be indeed a single news, without a repeating algorithm with affiliate. It shouldn't be blocked.

Here is a useless information for you: The founder of winfuture and me went to the same school. But we never met. It's true ;)

**Comment by BlazDT** [comment]
Please try these rules (I checked main page and news ticker):

```
winfuture.de#?#.topnews > div:has(span:contains(/(Anzeige)|Schnäppchen|Deal|sale|Tarif|Angebot/))
winfuture.de##.topnews > .clearfix
winfuture.de#?#div[class^="hp_"] div:has(> .topteaser:contains(/(Anzeige)|Schnäppchen|Deal|sale|Tarif|Angebot/))
winfuture.de##div[class^="hp_"] > div > div[style="display: none !important;"] + .clearfix
winfuture.de#?#.newsTicker > li:has(> a:contains(/(Anzeige)|Schnäppchen|Deal|sale|Tarif|Angebot/))
winfuture.de#?#.topnews > div[class]:has(> h2 > a[href*="/special/"][href*="/angebote/"])
```

MediaMarkt/Saturn/Notebooksbilliger/Amazon ads were shown to me.

**Comment by BlazDT** [comment]
Looks like non-designated ad on main page for me:
https://winfuture.de/videos/Hardware/Tamron-17-70-mm-f2.8-Di-III-A-RXD-Echt-starkes-Zoom-Objektiv-22924.html

**Comment by Morku** [comment]
wow, this looks great with the filters :) From my side, green light for Annoyance filter.
It might not filter all, like this one? https://winfuture.de/news,124141.html It's probably not part of the "daily news pattern".

winfuture.de seems to be partner of some YouTubers (ValueTech, AlexiBexi...) and upload the video on their page, like other trailers. It's actually not an Ad.
The "Werbung" in the one video is, because it's also in the original video: https://www.youtube.com/watch?v=-fDJ8BP06Gw
In germany, if the YouTuber got paid by the company they review or get the product for free, they have to mark it with Werbung. Might be the case here.

**Comment by BlazDT** [comment]
MediaMarkt one is hidden for me (or on which site do you see it)? I modified the rules list a few times which should hide it for you.

**Comment by Morku** [comment]
With the updated rules, can't see any Media-Markt/Saturn/Amazon/Notebooksbilliger Deals anymore :)

**Comment by AdamWr** [comment]
>@AdamWr what do you think about the topic? Personally I do not like those elements.

If these elements are some kind of ads, promotions or something like sponsored articles and are annoying, then I think it could be blocked in Annoyances filter.

**Comment by BlazDT** [comment]
Added.

**Comment by Morku** [comment]
@BlazDT 
<details><summary>Screenshot-1:</summary>

![win](https://user-images.githubusercontent.com/6276915/141282409-a9f878f5-cd54-4e46-8605-3c750ea63cd8.png)


</details><br/>

**Comment by BlazDT** [comment]
Modified a few rules regarding those ads.
