### ISSUE TITLE
Embedded links in Youtube videos get blocked by Annoyances filter

### ISSUE THREAD

**Issue by phantomcraft** [AdguardTeam/AdguardFilters#88836]
Is easy to reproduce, just enable "Annoyances" filter in configuration options and open a video of Youtube in which there is embedded links in it: https://youtu.be/YHc-c9hJMrU?t=272

This links should not be blocked, and honestly they don't annoy me.

I use 2 other Ads blockers, uBlock Origin and Ghostery together, and they don't remove this embedded links.

**Comment by Sergey-Lyapin** [comment]
Hello @phantomcraft, do you mean these elements?
![YT](https://user-images.githubusercontent.com/18536328/126804490-f4c40090-5df4-4002-a2b4-649b57b143d8.png)

**Comment by phantomcraft** [comment]
/\ Yes.

**Comment by Sergey-Lyapin** [comment]
@phantomcraft
Ok, I removed the rule for these elements.

**Comment by Morku** [comment]
Many years ago, I was wondering the same. It was clarified that this is Annoyance: https://forum.adguard.com/index.php?threads/www-youtube-com-watch-v-blocked-in-video-linking.28018/

**Comment by adranger** [comment]
Thank you for this change. This was something that had bothered me since I started using and contributing to Adguard filters too, because my relevant cards were hidden from my own videos.

It makes no sense to consider **end cards** hand-picked by the video creator himself/herself an annoyance, unless you also consider all automatic sidebar suggestions an even bigger annoyance. If that's the case, users can use third-party extensions to change the whole layout of the site.

**Comment by phantomcraft** [comment]
> @phantomcraft
> Ok, I removed the rule for these elements.

Thank you for the commit, now the links are working.

=)

**Comment by gwarser** [comment]
At the time when YT introduced these, many YT creators enabled them by default even for short, not prepared for this videos, and these tiles covered good content in many videos. Definitely annoyance.
